### ISSUE TITLE
clicking window close decorator does not stop the fun

### ISSUE THREAD

**Issue by stevenschlansker** [platipy/sarah-and-roberts-game#1]
After many hours of engrossing gameplay, users who are not (wo)manly enough to complete the game may wish to chicken out and quit.  They might try to do this by clicking the evil X decoration on the top right of the window.

It's not very effective.

![image](https://user-images.githubusercontent.com/129097/79480066-774adf80-7fc2-11ea-8ed7-fe879b81c8fb.png)

**Comment by sarahcstringer** [comment]
Thank you! Should be fixed now with https://github.com/platipy/sarah-and-roberts-game/commit/672b1552ee94cd2bea8ff15e5d694cee8b050018 :)
![Screen Shot 2020-04-16 at 9 44 26 AM](https://user-images.githubusercontent.com/13165465/79483247-e296b080-7fc6-11ea-83fa-23b901cde593.png)
